export const eventCreateTexts = {
  action: 'Создать объявление',
  title: 'Новое объявление о работах',
  description: 'Жители дома увидят его на главной',
  houseLabel: 'Дом',
  reasonLabel: 'Причина',
  reasonPlaceholder: 'Например, плановое отключение горячей воды',
  responsibleLabel: 'Ответственный',
  responsiblePlaceholder: 'Например, УК-1',
  entranceLabel: 'Подъезд',
  entrancePlaceholder: 'Необязательно',
  riserLabel: 'Стояк или зона',
  riserPlaceholder: 'Необязательно',
  fromLabel: 'Начало',
  toLabel: 'Окончание',
  submit: 'Опубликовать',
  cancel: 'Отмена',
  required: 'Заполните причину, ответственного и период работ',
  invalidRange: 'Окончание должно быть позже начала',
} as const
