export const incidentReportTexts = {
  title: 'Сообщить о проблеме',
  description: 'Определим ответственное ведомство и направим обращение по адресу',
  cancel: 'Отмена',
  steps: {
    description: 'Шаг 1 из 3 · Описание',
    routing: 'Шаг 2 из 3 · Ответственный',
    photo: 'Шаг 3 из 3 · Фото',
  },
  descriptionStep: {
    titleLabel: 'Кратко: что случилось?',
    titlePlaceholder: 'Например: нет горячей воды',
    label: 'Опишите проблему своими словами',
    placeholder: 'Например: нет горячей воды, сломан лифт, течёт крыша',
    hint: (min: number, max: number) => `От ${min} до ${max} символов`,
    counter: (current: number, max: number) => `${current} / ${max}`,
    submit: 'Далее',
    analyzingTitle: 'Определяем ответственного',
    analyzingDescription: 'Анализируем описание, это занимает несколько секунд',
  },
  routingStep: {
    ukTitle: 'Ответственный: ваша УК',
    otherTitle: 'Ответственный: не ваша УК',
    categoryLabel: 'Категория',
    authorityLabel: 'Ответственный',
    ukDescription: 'Заявку примет диспетчер вашей управляющей компании',
    otherDescription:
      'Управляющая компания не имеет права решать эту проблему. Чтобы решить вопрос быстрее, обращение нужно направить напрямую ответственному ведомству.',
    gosuslugiAction: 'Подать жалобу через Госуслуги.Решаем Вместе',
    detailsTitle: 'Уточните место (необязательно)',
    entranceLabel: 'Подъезд (необязательно)',
    entrancePlaceholder: 'Например, 2',
    floorZoneLabel: 'Этаж или зона (необязательно)',
    floorZonePlaceholder: 'Например, 5 этаж, мусоропровод',
    submit: 'Перейти к фото',
    back: 'Изменить описание',
  },
  fallback: {
    title: 'Не удалось определить автоматически',
    description: 'Не получилось определить категорию по описанию. Выберите ведомство и категорию вручную.',
    authorityLabel: 'Ведомство',
    categoryLabel: 'Категория проблемы',
    authorityPlaceholder: 'Выберите ведомство',
    categoryPlaceholder: 'Выберите категорию',
  },
  photoStep: {
    requiredTitle: 'Для этой категории нужно фото',
    requiredDescription: 'Снимок помогает УК отличить реальную проблему от спама',
    optionalTitle: 'Для этой категории фото необязательно',
    optionalDescription: 'Можно приложить снимок, если он есть — так заявку обработают быстрее',
    submit: 'Отправить заявку',
    back: 'Назад',
  },
  errors: {
    titleTooShort: (min: number) => `Кратко назовите проблему — минимум ${min} символа`,
    titleTooLong: (max: number) => `Название не должно превышать ${max} символов`,
    descriptionTooShort: (min: number) => `Опишите проблему подробнее — минимум ${min} символов`,
    descriptionTooLong: (max: number) => `Описание не должно превышать ${max} символов`,
    routingRequired: 'Выберите ведомство и категорию проблемы',
    photoRequired: 'Добавьте хотя бы одно фото проблемы',
  },
} as const
