export const incidentReportTexts = {
  title: 'Сообщить о проблеме',
  description: 'Заявка попадёт диспетчеру вашей УК',
  cancel: 'Отмена',
  a11y: { photoPreview: 'Предпросмотр фото' },
  detailsStep: 'Шаг 1 из 2 · Описание',
  photoStep: 'Шаг 2 из 2 · Фото',
  titleLabel: 'Что случилось?',
  titlePlaceholder: 'Например, нет горячей воды',
  descriptionLabel: 'Подробности',
  descriptionPlaceholder: 'Укажите подъезд, этаж или другие детали',
  entranceLabel: 'Подъезд',
  entrancePlaceholder: 'Например, 2',
  riserLabel: 'Стояк или зона',
  riserPlaceholder: 'Например, кухня на 5 этаже',
  severityLabel: 'Тип проблемы',
  critical: 'Авария',
  warning: 'Плановые работы',
  next: 'Перейти к фото',
  photoTitle: 'Подтвердите проблему фото',
  photoDescription: 'Снимок с камеры помогает УК отличить реальную проблему от спама.',
  choosePhoto: 'Выбрать фото',
  changePhoto: 'Выбрать другое фото',
  upload: 'Отправить обращение',
  retryUpload: 'Повторить отправку фото',
  back: 'Назад к описанию',
  photoHint: 'JPEG или PNG, до 10 МБ',
  photoRequired: 'Добавьте хотя бы одно фото проблемы',
  photoType: 'Поддерживаются только JPEG и PNG',
  photoSize: 'Размер фото не должен превышать 10 МБ',
  detailsRequired: 'Заполните заголовок и описание проблемы',
} as const
