export type {
  AnalyzeIncidentInput,
  AnalyzeIncidentResult,
  ConfirmResponse,
  CreateIncidentInput,
  Incident,
  IncidentAuthority,
  IncidentCategory,
  IncidentPhoto,
  IncidentListResponse,
  IncidentSeverity,
  IncidentStatus,
  IncidentSupporter,
  JoinResponse,
  MergeIncidentsInput,
  MergeIncidentsResult,
  PaginatedResidentRequests,
  ResidentRequest,
  PaginatedUkQueue,
  UkQueueItem,
} from './schema'
